### ISSUE TITLE
Windows compilation problems.

### ISSUE THREAD

**Issue by prime6809** [raspberrypi/openocd#38] opened 2021-06-21 08:39 UTC
Building under MINGW / MSYS causes one of two problems :

1) Using the current latest version of libusb (1.0.24-3) causes a segmentation fault.
2) Using the previous version 1.0.23, causes the picoprobe not to be detected.

Building under cygwin which has an earlier version of libusb (1.0.20-1), produces a working executable.

Cheers.

Phill.

**Comment by lurch** [comment] 2021-06-21 09:03
Duplicate of https://github.com/raspberrypi/picoprobe/issues/3 ?

**Comment by mcuee** [comment] 2022-07-13 05:50
https://github.com/raspberrypi/picoprobe/issues/3#issuecomment-1132810855

The following libusb issue has been resolved in libusb release 1.0.25. Latest libusb version is 1.0.26. It is recommended that you use libusb-1.0.26 to build openocd.
* https://github.com/libusb/libusb/issues/954

But WinUSB driver is still recommended and not libusb0.sys.

**Comment by mcuee** [comment] 2022-07-14 03:03
So this can be closed now.

**Closed** 2023-07-07 13:42 UTC
